name: CI/CD Pipeline

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run linting
        run: npm run lint
        
      - name: Run type checking
        run: npm run typecheck
        
      - name: Setup Prisma
        run: npx prisma generate
        
      - name: Run unit tests
        run: npm test
        
      - name: Install Playwright dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2
          
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
        
      - name: Start development server
        run: |
          npm run dev -- -p 3001 &
          sleep 5
          curl -s http://localhost:3001 > /dev/null || exit 1
          echo "Server is running on port 3001"
        
      - name: Run E2E tests
        run: npm run test:e2e -- --workers=4 --project=chromium
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: false
          PORT: 3001

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }} --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} 